# Generated by Django 2.1.15 on 2021-03-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210317_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='period_end_date',
            field=models.DateTimeField(default='1111-11-11 11:11'),
        ),
        migrations.AddField(
            model_name='alert',
            name='period_start_date',
            field=models.DateTimeField(default='1111-11-11 11:11'),
        ),
    ]
